exec: ../dist/build/encoding-mashup-server/encoding-mashup-server
args:
    - production
#host: encoding-mashup.csie.org # can replace with "*" to be the default app
host: localhost # can replace with "*" to be the default app
ssl: false # true would use https scheme for approot

# Static file hosts. Keter handles the serving for you.
static-hosts:
    #- host: static-encoding-mashup.csie.org
    - host: localhost
      root: ../static # relative to config file, just like the executable

